const crypto = require('crypto');
const axios = require('axios');

const LOGO_COLORS = [
  'bg-red-500', 'bg-indigo-600', 'bg-purple-500', 'bg-rose-500',
  'bg-amber-500', 'bg-emerald-500', 'bg-blue-600', 'bg-orange-500',
  'bg-teal-500', 'bg-cyan-500', 'bg-pink-500', 'bg-lime-600'
];

const COMPANY_LOGOS = {
  'tcs': 'https://logo.clearbit.com/tcs.com',
  'tata consultancy services': 'https://logo.clearbit.com/tcs.com',
  'tata cliq': 'https://logo.clearbit.com/tatacliq.com',
  'tata cliq fashion': 'https://logo.clearbit.com/tatacliq.com',
  'accenture': 'https://logo.clearbit.com/accenture.com',
  'capgemini': 'https://logo.clearbit.com/capgemini.com',
  'capgemini engineering': 'https://logo.clearbit.com/capgemini.com',
  'cognizant': 'https://logo.clearbit.com/cognizant.com',
  'cognizant technology solutions': 'https://logo.clearbit.com/cognizant.com',
  'infosys': 'https://logo.clearbit.com/infosys.com',
  'infosys bpm': 'https://logo.clearbit.com/infosys.com',
  'wipro': 'https://logo.clearbit.com/wipro.com',
  'hcl': 'https://logo.clearbit.com/hcltech.com',
  'hcltech': 'https://logo.clearbit.com/hcltech.com',
  'hcl technologies': 'https://logo.clearbit.com/hcltech.com',
  'tech mahindra': 'https://logo.clearbit.com/techmahindra.com',
  'techwave consulting india private': 'https://logo.clearbit.com/techwave.com',
  'ibm': 'https://logo.clearbit.com/ibm.com',
  'deloitte': 'https://logo.clearbit.com/deloitte.com',
  'google': 'https://logo.clearbit.com/google.com',
  'amazon': 'https://logo.clearbit.com/amazon.com',
  'microsoft': 'https://logo.clearbit.com/microsoft.com',
  'meta': 'https://logo.clearbit.com/meta.com',
  'apple': 'https://logo.clearbit.com/apple.com',
  'netflix': 'https://logo.clearbit.com/netflix.com',
  'adobe': 'https://logo.clearbit.com/adobe.com',
  'uber': 'https://logo.clearbit.com/uber.com',
  'flipkart': 'https://logo.clearbit.com/flipkart.com',
  'samsung': 'https://logo.clearbit.com/samsung.com',
  'oracle': 'https://logo.clearbit.com/oracle.com',
  'salesforce': 'https://logo.clearbit.com/salesforce.com',
  'linkedin': 'https://logo.clearbit.com/linkedin.com',
  'twitter': 'https://logo.clearbit.com/twitter.com',
  'spotify': 'https://logo.clearbit.com/spotify.com',
  'airbnb': 'https://logo.clearbit.com/airbnb.com',
  'stripe': 'https://logo.clearbit.com/stripe.com',
  'shopify': 'https://logo.clearbit.com/shopify.com',
  'paypal': 'https://logo.clearbit.com/paypal.com',
  'visa': 'https://logo.clearbit.com/visa.com',
  'goldman sachs': 'https://logo.clearbit.com/goldmansachs.com',
  'jp morgan': 'https://logo.clearbit.com/jpmorganchase.com',
  'morgan stanley': 'https://logo.clearbit.com/morganstanley.com',
  'capita': 'https://logo.clearbit.com/capita.co.uk',
  'ey': 'https://logo.clearbit.com/ey.com',
  'pwc': 'https://logo.clearbit.com/pwc.com',
  'pwc india': 'https://logo.clearbit.com/pwc.com',
  'kpmg': 'https://logo.clearbit.com/kpmg.com',
  'kpmg india': 'https://logo.clearbit.com/kpmg.com',
  'standard chartered bank': 'https://logo.clearbit.com/sc.com',
  'standard chartered': 'https://logo.clearbit.com/sc.com',
  'deutsche bank': 'https://logo.clearbit.com/db.com',
  'goldman sachs': 'https://logo.clearbit.com/goldmansachs.com',
  'natwest markets': 'https://logo.clearbit.com/natwest.com',
  'moody\'s': 'https://logo.clearbit.com/moodys.com',
  'moodys': 'https://logo.clearbit.com/moodys.com',
  'morningstar': 'https://logo.clearbit.com/morningstar.com',
  'nuvama group': 'https://logo.clearbit.com/nuvama.com',
  'nuvama asset services': 'https://logo.clearbit.com/nuvama.com',
  'nuvama wealth': 'https://logo.clearbit.com/nuvama.com',
  'kotak life': 'https://logo.clearbit.com/kotaklifeinsurance.com',
  'nykaa': 'https://logo.clearbit.com/nykaa.com',
  'ola electric': 'https://logo.clearbit.com/olaelectric.com',
  'ola': 'https://logo.clearbit.com/olacabs.com',
  'reliance industries limited': 'https://logo.clearbit.com/reliance.com',
  'reliance games': 'https://logo.clearbit.com/jio.com',
  'reliance jio': 'https://logo.clearbit.com/jio.com',
  'unacademy': 'https://logo.clearbit.com/unacademy.com',
  'upgrad': 'https://logo.clearbit.com/upgrad.com',
  'livspace': 'https://logo.clearbit.com/livspace.com',
  'happiest minds technologies': 'https://logo.clearbit.com/happiestminds.com',
  'firstsource': 'https://logo.clearbit.com/firstsource.com',
  'kissflow': 'https://logo.clearbit.com/kissflow.com',
  'godrej industries limited': 'https://logo.clearbit.com/godrej.com',
  'godrej': 'https://logo.clearbit.com/godrej.com',
  'ifb industries ltd': 'https://logo.clearbit.com/ifbindia.in',
  'biocon biologics': 'https://logo.clearbit.com/bioconbiologics.com',
  'biocon': 'https://logo.clearbit.com/biocon.com',
  'max healthcare': 'https://logo.clearbit.com/maxhealthcare.in',
  'honasa consumer ltd.': 'https://logo.clearbit.com/mamamearth.com',
  'dehaat': 'https://logo.clearbit.com/dehaat.com',
  'mokobara': 'https://logo.clearbit.com/mokobara.com',
  'euler motors': 'https://logo.clearbit.com/eulermotors.com',
  'cars24': 'https://logo.clearbit.com/cars24.in',
  'cars24 services private limited': 'https://logo.clearbit.com/cars24.in',
  'chai point': 'https://logo.clearbit.com/chaipoint.com',
  'hp': 'https://logo.clearbit.com/hp.com',
  'hewlett packard': 'https://logo.clearbit.com/hp.com',
  'ebay': 'https://logo.clearbit.com/ebay.com',
  'pfizer': 'https://logo.clearbit.com/pfizer.com',
  'deutsche bank': 'https://logo.clearbit.com/db.com',
  'moody\'s': 'https://logo.clearbit.com/moodys.com',
  'morningstar': 'https://logo.clearbit.com/morningstar.com',
  'criteo': 'https://logo.clearbit.com/criteo.com',
  'danaher': 'https://logo.clearbit.com/danaher.com',
  'ubisoft': 'https://logo.clearbit.com/ubisoft.com',
  'kyndryl': 'https://logo.clearbit.com/kyndryl.com',
  'hitachi solutions india': 'https://logo.clearbit.com/hitachi.com',
  'hitachi': 'https://logo.clearbit.com/hitachi.com',
  'renesas electronics': 'https://logo.clearbit.com/renesas.com',
  'capco': 'https://logo.clearbit.com/capco.com',
  'ecolab': 'https://logo.clearbit.com/ecolab.com',
  'lexisnexis legal & professional®': 'https://logo.clearbit.com/lexisnexis.com',
  'lexisnexis': 'https://logo.clearbit.com/lexisnexis.com',
  'virtusa': 'https://logo.clearbit.com/virtusa.com',
  'virtusa referral program': 'https://logo.clearbit.com/virtusa.com',
  'sopra steria': 'https://logo.clearbit.com/soprasteria.com',
  'emeritus': 'https://logo.clearbit.com/emeritus.org',
  'wise': 'https://logo.clearbit.com/wise.com',
  'msci': 'https://logo.clearbit.com/msci.com',
  'harman becker automotive systems manufacturing kft': 'https://logo.clearbit.com/harman.com',
  'harman': 'https://logo.clearbit.com/harman.com',
  'ifb': 'https://logo.clearbit.com/ifbindia.in',
  'firstsource': 'https://logo.clearbit.com/firstsource.com',
  'symphonyai': 'https://logo.clearbit.com/symphonyai.com',
  'cornerstone ondemand': 'https://logo.clearbit.com/cornerstoneondemand.com',
  'cornerstone ondemand': 'https://logo.clearbit.com/cornerstoneondemand.com',
  'infoblox': 'https://logo.clearbit.com/infoblox.com',
  'cloudester software llp': 'https://logo.clearbit.com/cloudester.com',
  'sopra steria': 'https://logo.clearbit.com/soprasteria.com',
  'indium software': 'https://logo.clearbit.com/indiumsoft.com',
  'larsen & toubro': 'https://logo.clearbit.com/larsentoubro.com',
  'l&t': 'https://logo.clearbit.com/larsentoubro.com',
  'l&t valves': 'https://logo.clearbit.com/larsentoubro.com',
  'ltim': 'https://logo.clearbit.com/ltimindtree.com',
  'ltimindtree': 'https://logo.clearbit.com/ltimindtree.com',
  'mindtree': 'https://logo.clearbit.com/mindtree.com',
  'tata elxsi': 'https://logo.clearbit.com/tataelxsi.com',
  'tata motors': 'https://logo.clearbit.com/tatamotors.com',
  'tata steel': 'https://logo.clearbit.com/tatasteel.com',
  'tata power': 'https://logo.clearbit.com/tatapower.com',
  'tata communications': 'https://logo.clearbit.com/tatacommunications.com',
  'tata aig': 'https://logo.clearbit.com/tataaig.com',
  'tata': 'https://logo.clearbit.com/tata.com',
  'adani': 'https://logo.clearbit.com/adanienterprise.com',
  'adani ports and sez': 'https://logo.clearbit.com/adanienterprise.com',
  'adani group': 'https://logo.clearbit.com/adanienterprise.com',
  'bajaj': 'https://logo.clearbit.com/bajajfinserv.in',
  'bajaj finserv': 'https://logo.clearbit.com/bajajfinserv.in',
  'bajaj allianz': 'https://logo.clearbit.com/bajajallianz.com',
  'sbi': 'https://logo.clearbit.com/sbi.co.in',
  'state bank of india': 'https://logo.clearbit.com/sbi.co.in',
  'hdfc bank': 'https://logo.clearbit.com/hdfcbank.com',
  'hdfc': 'https://logo.clearbit.com/hdfcbank.com',
  'icici bank': 'https://logo.clearbit.com/icicibank.com',
  'icici': 'https://logo.clearbit.com/icicibank.com',
  'axis bank': 'https://logo.clearbit.com/axisbank.com',
  'whirlpool': 'https://logo.clearbit.com/whirlpool.com',
  'siemens': 'https://logo.clearbit.com/siemens.com',
  'philips': 'https://logo.clearbit.com/philips.com',
  'bosch': 'https://logo.clearbit.com/bosch.com',
  'schneider electric': 'https://logo.clearbit.com/schneider-electric.com',
  'cisco': 'https://logo.clearbit.com/cisco.com',
  'intel': 'https://logo.clearbit.com/intel.com',
  'nvidia': 'https://logo.clearbit.com/nvidia.com',
  'dell': 'https://logo.clearbit.com/dell.com',
  'dell technologies': 'https://logo.clearbit.com/dell.com',
  'vmware': 'https://logo.clearbit.com/vmware.com',
  'atlassian': 'https://logo.clearbit.com/atlassian.com',
  'twilio': 'https://logo.clearbit.com/twilio.com',
  'zoom': 'https://logo.clearbit.com/zoom.us',
  'slack': 'https://logo.clearbit.com/slack.com',
  'dropbox': 'https://logo.clearbit.com/dropbox.com',
  'pinterest': 'https://logo.clearbit.com/pinterest.com',
  'snap': 'https://logo.clearbit.com/snap.com',
  'snapchat': 'https://logo.clearbit.com/snap.com',
  'twitch': 'https://logo.clearbit.com/twitch.tv',
  'github': 'https://logo.clearbit.com/github.com',
  'gitlab': 'https://logo.clearbit.com/gitlab.com',
  'figma': 'https://logo.clearbit.com/figma.com',
  'canva': 'https://logo.clearbit.com/canva.com',
  'zoomcar': 'https://logo.clearbit.com/zoomcar.com',
  'phonepe': 'https://logo.clearbit.com/phonepe.com',
  'phonepe': 'https://logo.clearbit.com/phonepe.com',
  'razorpay': 'https://logo.clearbit.com/razorpay.com',
  'paytm': 'https://logo.clearbit.com/paytm.com',
  'one97 communications': 'https://logo.clearbit.com/paytm.com',
  'swiggy': 'https://logo.clearbit.com/swiggy.com',
  'zomato': 'https://logo.clearbit.com/zomato.com',
  'meesho': 'https://logo.clearbit.com/meesho.com',
  'cred': 'https://logo.clearbit.com/cred.club',
  'credhive': 'https://logo.clearbit.com/credhive.com',
  'dream11': 'https://logo.clearbit.com/dream11.com',
  'dream sports': 'https://logo.clearbit.com/dreamsports.com',
  'freshworks': 'https://logo.clearbit.com/freshworks.com',
  'freshdesk': 'https://logo.clearbit.com/freshworks.com',
  'postman': 'https://logo.clearbit.com/postman.com',
  'zoho': 'https://logo.clearbit.com/zoho.com',
  'zenefits': 'https://logo.clearbit.com/zenefits.com',
  'uber': 'https://logo.clearbit.com/uber.com',
  'makeMyTrip': 'https://logo.clearbit.com/makemytrip.com',
  'make my trip': 'https://logo.clearbit.com/makemytrip.com',
  'oyo': 'https://logo.clearbit.com/oyorooms.com',
  'oyo rooms': 'https://logo.clearbit.com/oyorooms.com',
  'policybazaar': 'https://logo.clearbit.com/policybazaar.com',
  'policy bazaar': 'https://logo.clearbit.com/policybazaar.com',
  'ixigo': 'https://logo.clearbit.com/ixigo.com',
  'cleartrip': 'https://logo.clearbit.com/cleartrip.com',
  'practo': 'https://logo.clearbit.com/practo.com',
  'curefit': 'https://logo.clearbit.com/cure.fit',
  'cult.fit': 'https://logo.clearbit.com/cure.fit',
  ' Lenskart': 'https://logo.clearbit.com/lenskart.com',
  'lenskart': 'https://logo.clearbit.com/lenskart.com',
  'boat': 'https://logo.clearbit.com/boatlabs.com',
  'noise': 'https://logo.clearbit.com/gonoise.com',
  'fireboltt': 'https://logo.clearbit.com/fireboltt.com',
  'noise': 'https://logo.clearbit.com/gonoise.com',
  'zepto': 'https://logo.clearbit.com/zeptonow.com',
  'blinkit': 'https://logo.clearbit.com/blinkit.com',
  'bigbasket': 'https://logo.clearbit.com/bigbasket.com',
  'jio': 'https://logo.clearbit.com/jio.com',
  'jioMart': 'https://logo.clearbit.com/jiomart.com',
  'airtel': 'https://logo.clearbit.com/airtel.in',
  'vi': 'https://logo.clearbit.com/myvi.in',
  'vodafone idea': 'https://logo.clearbit.com/myvi.in',
  'bsnl': 'https://logo.clearbit.com/bsnl.co.in',
  'ntpc': 'https://logo.clearbit.com/ntpc.co.in',
  'ongc': 'https://logo.clearbit.com/ongcindia.com',
  'coal india': 'https://logo.clearbit.com/coalindia.in',
  'gail': 'https://logo.clearbit.com/gailonline.com',
  'hindalco': 'https://logo.clearbit.com/hindalco.com',
  'tata group': 'https://logo.clearbit.com/tata.com',
  'adani group': 'https://logo.clearbit.com/adanienterprise.com',
  'birla': 'https://logo.clearbit.com/adityabirla.com',
  'aditya birla group': 'https://logo.clearbit.com/adityabirla.com',
  'aditya birla': 'https://logo.clearbit.com/adityabirla.com',
  'mahindra': 'https://logo.clearbit.com/mahindra.com',
  'mahindra & mahindra': 'https://logo.clearbit.com/mahindra.com',
  'mahindra group': 'https://logo.clearbit.com/mahindra.com',
  'maruti suzuki': 'https://logo.clearbit.com/marutisuzuki.com',
  'hero motocorp': 'https://logo.clearbit.com/heromotocorp.com',
  'bajaj auto': 'https://logo.clearbit.com/bajajauto.com',
  'eicher motors': 'https://logo.clearbit.com/eicher.com',
  'ashok leyland': 'https://logo.clearbit.com/ashokleyland.com',
  'trent': 'https://logo.clearbit.com/trent-tata.com',
  'tata consumer products': 'https://logo.clearbit.com/tataconsumer.com',
  'itanza': 'https://logo.clearbit.com/itanza.com',
  'dabur': 'https://logo.clearbit.com/dabur.com',
  'marico': 'https://logo.clearbit.com/marico.com',
  'britannia': 'https://logo.clearbit.com/britannia.co.in',
  'itc': 'https://logo.clearbit.com/itcportal.com',
  'itc limited': 'https://logo.clearbit.com/itcportal.com',
  'hul': 'https://logo.clearbit.com/hul.co.in',
  'hindustan unilever': 'https://logo.clearbit.com/hul.co.in',
  'nestle india': 'https://logo.clearbit.com/nestle.in',
  'nestle': 'https://logo.clearbit.com/nestle.com',
  'colgate-palmolive': 'https://logo.clearbit.com/colgate.com',
  'pg': 'https://logo.clearbit.com/pg.com',
  'procter & gamble': 'https://logo.clearbit.com/pg.com',
  'unilever': 'https://logo.clearbit.com/unilever.com',
};

const FAKE_NAMES = [
  'TechCorp', 'InnovateAI', 'DataBridge', 'CloudBase',
  'NextWave', 'PrimeStack', 'ApexLogic', 'Radiant Systems',
  'Pinnacle Labs', 'Stealth Startup'
];

function generateId(title, company, source) {
  return crypto.createHash('md5').update(`${source}|${title}|${company}|${Date.now()}`).digest('hex');
}

function pickRandom(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function extractSkills(text) {
  const skillsList = [
    'React', 'Angular', 'Vue', 'Node.js', 'Express',
    'Python', 'Java', 'JavaScript', 'TypeScript', 'SQL',
    'MongoDB', 'PostgreSQL', 'Docker', 'AWS', 'GCP',
    'Figma', 'CSS', 'Tailwind CSS', 'Bootstrap', 'HTML',
    'Redux', 'GraphQL', 'Git', 'Linux', 'C++',
    'Ruby', 'Go', 'Rust', 'Kubernetes', 'Terraform',
    'Jenkins', 'Jira', 'Framer', 'Mulesoft', 'Tableau'
  ];
  const lower = text.toLowerCase();
  return skillsList.filter(skill => lower.includes(skill.toLowerCase()));
}

function getCompanyLogo(company) {
  if (!company) return '';
  const key = company.toLowerCase().trim();
  if (COMPANY_LOGOS[key]) return COMPANY_LOGOS[key];
  for (const [mapKey, url] of Object.entries(COMPANY_LOGOS)) {
    if (mapKey.length >= 4 && (key.startsWith(mapKey + ' ') || key.endsWith(' ' + mapKey) || (key.includes(' ' + mapKey + ' ')))) {
      return url;
    }
  }
  return '';
}

function createJobEntry(data) {
  const defaultSkills = data.skills || [];
  const extracted = extractSkills(data.description || '');
  const combined = [...new Set([...defaultSkills, ...extracted])];
  const companyName = data.company || pickRandom(FAKE_NAMES);
  return {
    id: data.id || generateId(data.title, companyName, data.source),
    title: data.title || 'Unknown Title',
    company: companyName,
    companyLogo: data.companyLogo || getCompanyLogo(companyName),
    logoColor: data.logoColor || pickRandom(LOGO_COLORS),
    logoText: companyName.charAt(0).toUpperCase(),
    location: data.location || 'Remote',
    salary: data.salary || 'Undisclosed',
    experience: data.experience || 'Fresher',
    employmentType: data.employmentType || 'Full-time',
    skills: combined.length > 0 ? combined : ['General'],
    description: data.description || '',
    responsibilities: data.responsibilities || [],
    benefits: data.benefits || [],
    postedAt: data.postedAt || 'Just now',
    duration: data.duration || null,
    matchScore: 0,
    source: data.source || 'web'
  };
}

async function fetchWithAxios(url, options = {}) {
  const headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
    'Accept-Language': 'en-US,en;q=0.5',
    'Referer': 'https://www.google.com/',
    'DNT': '1',
    'Connection': 'keep-alive',
    'Upgrade-Insecure-Requests': '1',
    ...options.headers
  };

  return axios.get(url, { headers, timeout: 15000, ...options });
}

function generateDescription(job) {
  return `${job.title} at ${job.company}. ${job.description || 'We are looking for a passionate individual to join our team and contribute to exciting projects.'} Learn, innovate, and grow with us.`;
}

module.exports = {
  generateId, pickRandom, extractSkills, createJobEntry, getCompanyLogo,
  FAKE_NAMES, LOGO_COLORS, COMPANY_LOGOS, fetchWithAxios, generateDescription
};
